import { Skill } from './types';

export const SKILL_ICONS: Record<string, string> = {
  [Skill.Painter]: '🎨',
  [Skill.Mason]: '🧱',
  [Skill.Helper]: '🏗️',
  [Skill.Plumber]: '🚰',
  [Skill.Electrician]: '💡',
  [Skill.Carpenter]: '🪑',
  [Skill.TileWorker]: '⬛',
  [Skill.Welder]: '🔥',
  [Skill.Cleaner]: '🧹',
  [Skill.LoadingWorker]: '📦',
  [Skill.Other]: '🔧'
};

export const SKILLS_LIST = Object.values(Skill);

export const AREAS_LIST = [
  "Vaishali Nagar",
  "Civil Lines",
  "Old City",
  "Malviya Nagar",
  "Raja Park",
  "Mansarovar",
  "Jhotwara",
  "Sodala",
  "Tonk Road",
  "C-Scheme",
  "Amer Road",
  "Sanganer"
];

export const TRANSLATIONS = {
  en: {
    app_name: "KaamChowk",
    tagline: "India's Online Labour Market",
    login: "Login",
    register: "Join Now",
    phone: "Mobile Number",
    password: "Password / OTP",
    otp_placeholder: "4 Digits",
    submit: "Done",
    role_selection: "Who are you?",
    im_worker: "I want Work",
    im_employer: "I need Workers",
    welcome: "Namaste",
    available_today: "Are you ready to work?",
    mark_available: "I am Available",
    mark_unavailable: "I am Busy Today",
    you_are_available: "Employers can see you now",
    find_work: "Find Jobs",
    my_profile: "Profile",
    name: "Full Name",
    skills: "Your Skill",
    area: "Your Area",
    wage: "Daily Wage (₹)",
    experience: "Experience",
    photo: "Selfie / Photo",
    pending_approval: "Verifying Profile...",
    approved: "Verified Account",
    rejected: "Action Required",
    post_job: "Post Job",
    find_workers: "Search",
    my_jobs: "My Posts",
    contact: "Call Now",
    rate: "Rate",
    admin_panel: "Admin Panel",
    add_worker: "Add Worker",
    pending_workers: "Pending",
    active_workers: "Active",
    approve: "Approve",
    reject: "Reject",
    logout: "Log Out",
    search_placeholder: "Search area...",
    no_results: "No active results found.",
    job_posted: "Job Posted Successfully!",
    worker_added: "Worker onboarded!",
    available_badge: "ONLINE",
    years: "yrs",
    per_day: "/day",
    workers_needed: "Workers Needed",
    date: "Date",
    description: "Details",
    save: "Save",
    cancel: "Cancel",
    confirm: "Confirm",
    ratings: "Rating",
    workers: "Labour",
    employers: "Hirers",
    jobs: "Jobs",
    loading: "Loading Chowk...",
    verify: "Verify",
    demo_mode: "Demo Login: 9999999999 (Admin)",
    enter_reason: "Reason?",
    next: "Next",
    back: "Back",
    select_skill: "Select Skill",
    urgent: "Urgent",
    verified: "Verified",
    book_now: "Book",
    posted_by: "Posted By",
    type_area: "Or Type Your Area",
    detect_location: "Detect Location",
    map_view: "Map View",
    list_view: "List View",
    sos_button: "SOS / Help",
    sos_alert: "Emergency Alert Sent to Admin & Local Contacts!",
    sos_modal_title: "EMERGENCY SOS",
    call_police: "Call Police (100)",
    call_ambulance: "Call Ambulance (108)",
    call_admin: "Call Helpline",
    sending_loc: "Sending Location...",
    loc_sent: "Alert Sent!",
    bio: "About Me / Bio",
    edit_profile: "Edit Profile",
    save_changes: "Save Changes",
    bio_placeholder: "Describe your work style...",
    delete_post: "Delete Post",
    delete_confirm: "Are you sure you want to delete this job?"
  },
  hi: {
    app_name: "काम चौक",
    tagline: "भारत का ऑनलाइन मज़दूर बाज़ार",
    login: "लॉगिन",
    register: "जुड़ें",
    phone: "मोबाइल नंबर",
    password: "पासवर्ड / OTP",
    otp_placeholder: "4 अंक",
    submit: "हो गया",
    role_selection: "आप कौन हैं?",
    im_worker: "मुझे काम चाहिए",
    im_employer: "मुझे मज़दूर चाहिए",
    welcome: "नमस्ते",
    available_today: "क्या आज काम पर जाओगे?",
    mark_available: "हाँ, मैं खाली हूँ",
    mark_unavailable: "नहीं, आज काम है",
    you_are_available: "मालिक आपको देख रहे हैं",
    find_work: "काम ढूँढें",
    my_profile: "प्रोफाइल",
    name: "पूरा नाम",
    skills: "क्या काम करते हो?",
    area: "इलाका",
    wage: "दिहाड़ी (₹)",
    experience: "अनुभव",
    photo: "फोटो",
    pending_approval: "जांच चल रही है...",
    approved: "सत्यापित खाता",
    rejected: "अस्वीकृत",
    post_job: "काम डालें",
    find_workers: "मज़दूर खोजें",
    my_jobs: "मेरी पोस्ट",
    contact: "कॉल करें",
    rate: "रेटिंग",
    admin_panel: "एडमिन",
    add_worker: "जोड़ें",
    pending_workers: "लंबित",
    active_workers: "सक्रिय",
    approve: "मंजूर",
    reject: "रद्द",
    logout: "बाहर निकलें",
    search_placeholder: "इलाका खोजें...",
    no_results: "कोई परिणाम नहीं मिला",
    job_posted: "काम पोस्ट हो गया!",
    worker_added: "जोड़ दिया गया!",
    available_badge: "ऑनलाइन",
    years: "साल",
    per_day: "/दिन",
    workers_needed: "कितने लोग?",
    date: "तारीख",
    description: "विवरण",
    save: "सेव",
    cancel: "रद्द",
    confirm: "पक्का करें",
    ratings: "रेटिंग",
    workers: "मज़दूर",
    employers: "मालिक",
    jobs: "नौकरियां",
    loading: "चौक खुल रहा है...",
    verify: "जांचें",
    demo_mode: "डेमो लॉगिन: 9999999999",
    enter_reason: "कारण?",
    next: "आगे",
    back: "पीछे",
    select_skill: "हुनर चुनें",
    urgent: "ज़रूरी",
    verified: "वेरीफाइड",
    book_now: "बुक करें",
    posted_by: "काम देने वाले",
    type_area: "या अपना इलाका लिखें",
    detect_location: "मेरी लोकेशन लें",
    map_view: "मैप देखें",
    list_view: "लिस्ट देखें",
    sos_button: "मदद (SOS)",
    sos_alert: "आपातकालीन संदेश भेज दिया गया है!",
    sos_modal_title: "आपातकालीन सहायता (SOS)",
    call_police: "पुलिस को बुलाओ (100)",
    call_ambulance: "एम्बुलेंस (108)",
    call_admin: "हेल्पलाइन पर कॉल करें",
    sending_loc: "लोकेशन भेज रहे हैं...",
    loc_sent: "संदेश भेज दिया!",
    bio: "मेरे बारे में",
    edit_profile: "प्रोफाइल बदलें",
    save_changes: "सेव करें",
    bio_placeholder: "अपने काम के बारे में बताएं...",
    delete_post: "पोस्ट हटाएँ",
    delete_confirm: "क्या आप यह पोस्ट हटाना चाहते हैं?"
  }
};